### ISSUE TITLE
OSStats.py script not executing and throwing  exception while processing 

### ISSUE THREAD

**Issue by jitender-gahlot** [Redislabs-Solution-Architects/osstats#3]
<img width="1432" alt="OSS error" src="https://user-images.githubusercontent.com/5260366/157458059-1af19ee6-1c79-4f1c-bcc0-157e041cbee1.png">

**Comment by thomasefthymiou78** [comment]
The above error was produced while parsing the following info command data:


```
127.0.0.1:6379> info
# Server
redis_version:5.0.5
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:5a2ebb32924941ad
redis_mode:standalone
os:Linux 3.10.0-514.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:4.8.5
process_id:31660
run_id:d7ddfbef14c9e0f73356aec6b18bec8621430b48
tcp_port:6379
uptime_in_seconds:9031206
uptime_in_days:104
hz:10
configured_hz:10
lru_clock:2996067
executable:/usr/local/bin/redis-server
config_file:/apps/redis-5.0.5/6379.conf
# Clients
connected_clients:285
client_recent_max_input_buffer:163227
client_recent_max_output_buffer:123024
blocked_clients:0
# Memory
used_memory:78456195056
used_memory_human:73.07G
used_memory_rss:84013170688
used_memory_rss_human:78.24G
used_memory_peak:80369154104
used_memory_peak_human:74.85G
used_memory_peak_perc:97.62%
used_memory_overhead:335154637
used_memory_startup:791400
used_memory_dataset:78121040419
used_memory_dataset_perc:99.57%
allocator_allocated:78456408592
allocator_active:82965667840
allocator_resident:84260474880
total_system_memory:139254116352
total_system_memory_human:129.69G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.06
allocator_frag_bytes:4509259248
allocator_rss_ratio:1.02
allocator_rss_bytes:1294807040
rss_overhead_ratio:1.00
rss_overhead_bytes:-247304192
mem_fragmentation_ratio:1.07
mem_fragmentation_bytes:5557096624
mem_not_counted_for_evict:0
mem_replication_backlog:1048576
mem_clients_slaves:66616
mem_clients_normal:8163509
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0
# Persistence
loading:0
rdb_changes_since_last_save:6222868378
rdb_bgsave_in_progress:0
rdb_last_save_time:1622826032
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:1021
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:2951110656
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
# Stats
total_connections_received:3562055
total_commands_processed:17180320355
instantaneous_ops_per_sec:3004
total_net_input_bytes:18476419094576
total_net_output_bytes:50009501337953
instantaneous_input_kbps:4166.55
instantaneous_output_kbps:10479.00
rejected_connections:0
sync_full:13
sync_partial_ok:0
sync_partial_err:9
expired_keys:1094786684
expired_stale_perc:29.27
expired_time_cap_reached_count:159649
evicted_keys:0
keyspace_hits:6547403055
keyspace_misses:821903033
pubsub_channels:1
pubsub_patterns:0
latest_fork_usec:2544686
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
# Replication
role:master
connected_slaves:2
slave0:ip=10.2.114.56,port=6379,state=online,offset=17830412328929,lag=1
slave1:ip=10.59.100.245,port=6379,state=online,offset=17830410884771,lag=1
master_replid:6bfc3bc7effbc66b8a7cdf679ffceea7fd7bfee5
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:17830413796905
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:17830412748330
repl_backlog_histlen:1048576
# CPU
used_cpu_sys:2388481.028276
used_cpu_user:1253996.507236
used_cpu_sys_children:2135.057612
used_cpu_user_children:7922.399921
# Cluster
cluster_enabled:0
# Keyspace
db0:keys=4552488,expires=1763405,avg_ttl=26295831

**Comment by thomasefthymiou78** [comment]
Another interesting find about the above might be found here ... https://github.com/DataDog/integrations-core/pull/2356

In short ... Collection breaks with a KeyError when cmdstat_host: is present in commandstats output (legit use case introduced with https://github.com/redis/redis/commit/a81a92ca2ceba364f4bb51efde9284d939e7ff47)

**Comment by jitender-gahlot** [comment]
![cluster nodes output](https://user-images.githubusercontent.com/5260366/157500600-ee63207c-8b69-40cb-b6c6-1553f8972a8c.png)

**Comment by jitender-gahlot** [comment]
~/redis-labs/osstats$ python osstats.py

The output will be stored in OssStats.xlsx

Connecting to redis-db1 database ..

Connected to redis-db1 database

Traceback (most recent call last):

  File "osstats.py", line 440, in <module>

    main()

  File "osstats.py", line 433, in main

    wb = process_database(dict(config.items(section)), section, wb, args.duration)

  File "osstats.py", line 362, in process_database

    nodes = client.execute_command('cluster nodes')

  File "/home/ubuntu/redis-labs/osstats/.env/lib/python3.8/site-packages/redis/client.py", line 1176, in execute_command

    return conn.retry.call_with_retry(

  File "/home/ubuntu/redis-labs/osstats/.env/lib/python3.8/site-packages/redis/retry.py", line 45, in call_with_retry

    return do()

  File "/home/ubuntu/redis-labs/osstats/.env/lib/python3.8/site-packages/redis/client.py", line 1177, in <lambda>

    lambda: self._send_command_parse_response(

  File "/home/ubuntu/redis-labs/osstats/.env/lib/python3.8/site-packages/redis/client.py", line 1153, in _send_command_parse_response

    return self.parse_response(conn, command_name, **options)

  File "/home/ubuntu/redis-labs/osstats/.env/lib/python3.8/site-packages/redis/client.py", line 1198, in parse_response

    return self.response_callbacks[command_name](response, **options)

  File "/home/ubuntu/redis-labs/osstats/.env/lib/python3.8/site-packages/redis/client.py", line 490, in parse_cluster_nodes

    return dict(_parse_node_line(str_if_bytes(node)) for node in response)

  File "/home/ubuntu/redis-labs/osstats/.env/lib/python3.8/site-packages/redis/client.py", line 490, in <genexpr>

    return dict(_parse_node_line(str_if_bytes(node)) for node in response)

  File "/home/ubuntu/redis-labs/osstats/.env/lib/python3.8/site-packages/redis/client.py", line 466, in _parse_node_line

    line_items = line.split(" ")

AttributeError: 'int' object has no attribute 'split'





config.ini : 




[redis-db1]
host        = 172.31.216.200
port        = 7000
tls         =
username    =
password    =

[redis-db2]
host        = 172.31.216.201
port        = 7001
tls         =
username    =
password    =

[redis-db3]
host        = 172.31.216.202
port        = 7002
tls         =
username    =
password    =

[redis-db4]
host        = 172.31.216.203
port        = 7003
tls         =
username    =
password    =

[redis-db5]
host        = 172.31.216.204
port        = 7004
tls         =
username    =
password    =

[redis-db6]
host        = 172.31.216.205
port        = 7005
tls         =
username    =
password    =
